version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db_ucn_dge
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ucn-dge

volumes:
  mongo-data:
